"""initial_schema

Revision ID: bd816eeb33bf
Revises: 
Create Date: 2026-05-16 01:02:12.310239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd816eeb33bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_logs_created_at'), 'api_logs', ['created_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=30), nullable=True),
    sa.Column('exchange_short', sa.String(length=20), nullable=True),
    sa.Column('company_name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('ceo', sa.String(length=200), nullable=True),
    sa.Column('employees', sa.BigInteger(), nullable=True),
    sa.Column('ipo_date', sa.Date(), nullable=True),
    sa.Column('is_etf', sa.Boolean(), nullable=False),
    sa.Column('is_actively_trading', sa.Boolean(), nullable=False),
    sa.Column('market_cap', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('vol_avg', sa.BigInteger(), nullable=True),
    sa.Column('last_dividend', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('data_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_country'), 'companies', ['country'], unique=False)
    op.create_index(op.f('ix_companies_exchange'), 'companies', ['exchange'], unique=False)
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False)
    op.create_index(op.f('ix_companies_sector'), 'companies', ['sector'], unique=False)
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=True)
    op.create_table('stock_quotes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('change', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('change_percent', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('avg_volume', sa.BigInteger(), nullable=True),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('previous_close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('year_high', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('year_low', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_market_open', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_quotes_ticker'), 'stock_quotes', ['ticker'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('verification_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preferences', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_password_reset_token'), 'users', ['password_reset_token'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_verification_token'), 'users', ['verification_token'], unique=False)
    op.create_table('balance_sheets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('period_end_date', sa.Date(), nullable=False),
    sa.Column('reported_currency', sa.String(length=10), nullable=True),
    sa.Column('cash_and_equivalents', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('short_term_investments', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('cash_and_short_term_investments', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('net_receivables', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('inventory', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('other_current_assets', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('total_current_assets', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('property_plant_equipment_net', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('goodwill', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('intangible_assets', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('long_term_investments', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('other_non_current_assets', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('total_non_current_assets', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('total_assets', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('accounts_payable', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('short_term_debt', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('deferred_revenue', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('other_current_liabilities', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('total_current_liabilities', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('long_term_debt', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('deferred_tax_liabilities', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('other_non_current_liabilities', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('total_non_current_liabilities', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('total_liabilities', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('common_stock', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('retained_earnings', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('accumulated_other_comprehensive_income', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('other_stockholder_equity', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('total_stockholder_equity', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('total_equity', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('total_liabilities_and_equity', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('minority_interest', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('net_debt', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('total_debt', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('cs_cash_pct', sa.Float(), nullable=True),
    sa.Column('cs_receivables_pct', sa.Float(), nullable=True),
    sa.Column('cs_inventory_pct', sa.Float(), nullable=True),
    sa.Column('cs_current_assets_pct', sa.Float(), nullable=True),
    sa.Column('cs_ppe_pct', sa.Float(), nullable=True),
    sa.Column('cs_goodwill_pct', sa.Float(), nullable=True),
    sa.Column('cs_total_current_liabilities_pct', sa.Float(), nullable=True),
    sa.Column('cs_total_debt_pct', sa.Float(), nullable=True),
    sa.Column('cs_total_liabilities_pct', sa.Float(), nullable=True),
    sa.Column('cs_equity_pct', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period', 'period_end_date', name='uq_balance_sheet_period')
    )
    op.create_index(op.f('ix_balance_sheets_company_id'), 'balance_sheets', ['company_id'], unique=False)
    op.create_index(op.f('ix_balance_sheets_period'), 'balance_sheets', ['period'], unique=False)
    op.create_index(op.f('ix_balance_sheets_period_end_date'), 'balance_sheets', ['period_end_date'], unique=False)
    op.create_index(op.f('ix_balance_sheets_ticker'), 'balance_sheets', ['ticker'], unique=False)
    op.create_table('cash_flow_statements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('period_end_date', sa.Date(), nullable=False),
    sa.Column('reported_currency', sa.String(length=10), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('depreciation_amortization', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('stock_based_compensation', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('deferred_income_tax', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('change_in_working_capital', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('accounts_receivable_changes', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('inventory_changes', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('accounts_payable_changes', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('other_operating_activities', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('net_cash_from_operating', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('capex', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('acquisitions', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('purchases_of_investments', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('sales_of_investments', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('other_investing_activities', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('net_cash_from_investing', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('debt_repayment', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('common_stock_issued', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('common_stock_repurchased', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('dividends_paid', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('other_financing_activities', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('net_cash_from_financing', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('effect_of_exchange_rate', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('net_change_in_cash', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('cash_end_of_period', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('cash_beginning_of_period', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('free_cash_flow', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('cs_net_income_pct', sa.Float(), nullable=True),
    sa.Column('cs_da_pct', sa.Float(), nullable=True),
    sa.Column('cs_sbc_pct', sa.Float(), nullable=True),
    sa.Column('cs_working_capital_pct', sa.Float(), nullable=True),
    sa.Column('cs_capex_pct', sa.Float(), nullable=True),
    sa.Column('cs_fcf_pct', sa.Float(), nullable=True),
    sa.Column('cs_investing_pct', sa.Float(), nullable=True),
    sa.Column('cs_financing_pct', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period', 'period_end_date', name='uq_cashflow_period')
    )
    op.create_index(op.f('ix_cash_flow_statements_company_id'), 'cash_flow_statements', ['company_id'], unique=False)
    op.create_index(op.f('ix_cash_flow_statements_period'), 'cash_flow_statements', ['period'], unique=False)
    op.create_index(op.f('ix_cash_flow_statements_period_end_date'), 'cash_flow_statements', ['period_end_date'], unique=False)
    op.create_index(op.f('ix_cash_flow_statements_ticker'), 'cash_flow_statements', ['ticker'], unique=False)
    op.create_table('financial_ratios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('period_end_date', sa.Date(), nullable=False),
    sa.Column('gross_margin', sa.Float(), nullable=True),
    sa.Column('operating_margin', sa.Float(), nullable=True),
    sa.Column('ebitda_margin', sa.Float(), nullable=True),
    sa.Column('net_margin', sa.Float(), nullable=True),
    sa.Column('roa', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('roic', sa.Float(), nullable=True),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('pb_ratio', sa.Float(), nullable=True),
    sa.Column('ps_ratio', sa.Float(), nullable=True),
    sa.Column('peg_ratio', sa.Float(), nullable=True),
    sa.Column('ev_ebitda', sa.Float(), nullable=True),
    sa.Column('fcf_yield', sa.Float(), nullable=True),
    sa.Column('current_ratio', sa.Float(), nullable=True),
    sa.Column('quick_ratio', sa.Float(), nullable=True),
    sa.Column('cash_ratio', sa.Float(), nullable=True),
    sa.Column('debt_to_equity', sa.Float(), nullable=True),
    sa.Column('debt_to_assets', sa.Float(), nullable=True),
    sa.Column('interest_coverage', sa.Float(), nullable=True),
    sa.Column('net_debt_to_ebitda', sa.Float(), nullable=True),
    sa.Column('fcf_per_share', sa.Float(), nullable=True),
    sa.Column('ocf_conversion', sa.Float(), nullable=True),
    sa.Column('capex_intensity', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period', 'period_end_date', name='uq_ratios_period')
    )
    op.create_index(op.f('ix_financial_ratios_company_id'), 'financial_ratios', ['company_id'], unique=False)
    op.create_index(op.f('ix_financial_ratios_period'), 'financial_ratios', ['period'], unique=False)
    op.create_index(op.f('ix_financial_ratios_ticker'), 'financial_ratios', ['ticker'], unique=False)
    op.create_table('historical_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('adj_close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('vwap', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('change', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('change_percent', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'date', name='uq_historical_price_company_date')
    )
    op.create_index(op.f('ix_historical_prices_date'), 'historical_prices', ['date'], unique=False)
    op.create_table('income_statements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('period_end_date', sa.Date(), nullable=False),
    sa.Column('reported_currency', sa.String(length=10), nullable=True),
    sa.Column('cik', sa.String(length=20), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('cost_of_revenue', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('gross_profit', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('research_and_development', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('selling_general_administrative', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('other_operating_expenses', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('total_operating_expenses', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('operating_income', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('interest_income', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('interest_expense', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('total_other_income_expense', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('ebitda', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('depreciation_amortization', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('income_before_tax', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('income_tax_expense', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('net_income_attributable', sa.Numeric(precision=24, scale=0), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('eps_diluted', sa.Float(), nullable=True),
    sa.Column('shares_outstanding', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('shares_diluted', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('cs_cost_of_revenue_pct', sa.Float(), nullable=True),
    sa.Column('cs_gross_profit_pct', sa.Float(), nullable=True),
    sa.Column('cs_rd_pct', sa.Float(), nullable=True),
    sa.Column('cs_sga_pct', sa.Float(), nullable=True),
    sa.Column('cs_total_opex_pct', sa.Float(), nullable=True),
    sa.Column('cs_operating_income_pct', sa.Float(), nullable=True),
    sa.Column('cs_ebitda_pct', sa.Float(), nullable=True),
    sa.Column('cs_net_income_pct', sa.Float(), nullable=True),
    sa.Column('yoy_revenue_growth', sa.Float(), nullable=True),
    sa.Column('yoy_gross_profit_growth', sa.Float(), nullable=True),
    sa.Column('yoy_operating_income_growth', sa.Float(), nullable=True),
    sa.Column('yoy_net_income_growth', sa.Float(), nullable=True),
    sa.Column('yoy_eps_growth', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period', 'period_end_date', name='uq_income_stmt_period')
    )
    op.create_index(op.f('ix_income_statements_company_id'), 'income_statements', ['company_id'], unique=False)
    op.create_index(op.f('ix_income_statements_period'), 'income_statements', ['period'], unique=False)
    op.create_index(op.f('ix_income_statements_period_end_date'), 'income_statements', ['period_end_date'], unique=False)
    op.create_index(op.f('ix_income_statements_ticker'), 'income_statements', ['ticker'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_portfolio_user_name')
    )
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('device_info', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_watchlist_user_name')
    )
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    op.create_table('portfolio_holdings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('shares', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_holdings_portfolio_id'), 'portfolio_holdings', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_portfolio_holdings_ticker'), 'portfolio_holdings', ['ticker'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('watchlist_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('alert_price_above', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('alert_price_below', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', 'ticker', name='uq_watchlist_ticker')
    )
    op.create_index(op.f('ix_watchlist_items_ticker'), 'watchlist_items', ['ticker'], unique=False)
    op.create_index(op.f('ix_watchlist_items_watchlist_id'), 'watchlist_items', ['watchlist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_items_watchlist_id'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_ticker'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_portfolio_holdings_ticker'), table_name='portfolio_holdings')
    op.drop_index(op.f('ix_portfolio_holdings_portfolio_id'), table_name='portfolio_holdings')
    op.drop_table('portfolio_holdings')
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_income_statements_ticker'), table_name='income_statements')
    op.drop_index(op.f('ix_income_statements_period_end_date'), table_name='income_statements')
    op.drop_index(op.f('ix_income_statements_period'), table_name='income_statements')
    op.drop_index(op.f('ix_income_statements_company_id'), table_name='income_statements')
    op.drop_table('income_statements')
    op.drop_index(op.f('ix_historical_prices_date'), table_name='historical_prices')
    op.drop_table('historical_prices')
    op.drop_index(op.f('ix_financial_ratios_ticker'), table_name='financial_ratios')
    op.drop_index(op.f('ix_financial_ratios_period'), table_name='financial_ratios')
    op.drop_index(op.f('ix_financial_ratios_company_id'), table_name='financial_ratios')
    op.drop_table('financial_ratios')
    op.drop_index(op.f('ix_cash_flow_statements_ticker'), table_name='cash_flow_statements')
    op.drop_index(op.f('ix_cash_flow_statements_period_end_date'), table_name='cash_flow_statements')
    op.drop_index(op.f('ix_cash_flow_statements_period'), table_name='cash_flow_statements')
    op.drop_index(op.f('ix_cash_flow_statements_company_id'), table_name='cash_flow_statements')
    op.drop_table('cash_flow_statements')
    op.drop_index(op.f('ix_balance_sheets_ticker'), table_name='balance_sheets')
    op.drop_index(op.f('ix_balance_sheets_period_end_date'), table_name='balance_sheets')
    op.drop_index(op.f('ix_balance_sheets_period'), table_name='balance_sheets')
    op.drop_index(op.f('ix_balance_sheets_company_id'), table_name='balance_sheets')
    op.drop_table('balance_sheets')
    op.drop_index(op.f('ix_users_verification_token'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_password_reset_token'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stock_quotes_ticker'), table_name='stock_quotes')
    op.drop_table('stock_quotes')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_index(op.f('ix_companies_sector'), table_name='companies')
    op.drop_index(op.f('ix_companies_industry'), table_name='companies')
    op.drop_index(op.f('ix_companies_exchange'), table_name='companies')
    op.drop_index(op.f('ix_companies_country'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_logs_created_at'), table_name='api_logs')
    op.drop_table('api_logs')
    # ### end Alembic commands ###
